# Generated by Django 3.2.11 on 2022-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='thumbline',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
